name: Deploy docs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Bow repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.0.0.app/Contents/Developer
    - name: Generate microsite
      run: |
        brew update
        brew install nef
        brew install sourcekitten
        gem install bundler -v 2.0.2
        gem install cocoapods -v 1.9.1
        ./scripts/gen-docs.rb
    - name: Deploy microsite
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./pub-dir
        disable_nojekyll: true
